cask_args appdir: '/Applications'

tap 'homebrew/bundle'
#tap 'puma/puma'

#brew 'gcc'
#brew 'coreutils'
brew 'go'
#brew 'jp2a'
brew 'jq'
brew 'openssl'
brew 'postgresql'
#brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'wget'
brew 'yarn'
#brew 'akamai'
brew 'awscli'
brew 'docker-machine'
brew 'docker-machine-driver-xhyve'
brew 'git'
#brew 'kubernetes-cli'
#brew 'kubernetes-helm'
#brew 'kubetail'
brew 'neovim'
brew 'nvm'
#brew 'phraseapp'
#brew 'python3'
#brew 'terraform'
brew 'tmux'
brew 'zsh'
#brew 'mosh'
#brew 'ctags'
#brew 'fzf'
#brew 'homebrew/cask/android-platform-tools'
#brew 'iproute2mac'
#brew 'redis'

# PHP
brew 'composer'

