alias reload!='. ~/.zshrc'
alias cls='clear' # Good 'ol Clear Screen command
alias ctags="`brew --prefix`/bin/ctags"
alias k="kubectl"
alias t='terraform'
alias i='istioctl'
alias s='skaffold'
alias v="nvim"
alias c="code-insiders"
alias ls="lsd"
alias bootstrap='$HOME/.dotfiles/script/bootstrap'
alias wake="caffeinate -u -t 28800" # 8 hours
alias sleepnow="pmset sleepnow"
# alias timeout="`gtimeout`"
